name: Generate Android Mirrors Classes

on:
  workflow_dispatch: # Tombol manual di tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Process Framework
        run: |
          echo "🚀 Memulai Mirroring Framework..."
          ./gradlew run --args="input/framework.jar output_mirrors"

      - name: Process Services
        run: |
          echo "🚀 Memulai Mirroring Services..."
          ./gradlew run --args="input/services.jar output_mirrors"

      - name: Check Output
        run: |
          echo "📊 Statistik Output:"
          find output_mirrors -name "*.class" | wc -l
          echo " file mirror berhasil dibuat."

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android-Mirror-Classes
          path: output_mirrors/
          retention-days: 7
